# Generated by Django 3.2.1 on 2021-05-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlmodel',
            name='serve_count',
            field=models.IntegerField(default=0),
        ),
    ]
